// <auto-generated />
using System;
using HRManagementSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(HRManagementSystemDbContext))]
    [Migration("20260626041405_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRManagementSystem.Domains.Entities.Benefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BenefitType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BenefitType");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Benefits", t =>
                        {
                            t.HasCheckConstraint("CK_Benefit_Amount", "Amount >= 0");
                        });

                    b.HasDiscriminator<string>("BenefitType").HasValue("Benefit");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HRManagementSystem.Domains.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId")
                        .IsUnique()
                        .HasFilter("[ManagerId] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments", t =>
                        {
                            t.HasCheckConstraint("CK_Department_Name", "LEN(TRIM(Name)) > 0");
                        });
                });

            modelBuilder.Entity("HRManagementSystem.Domains.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateOfHire")
                        .HasColumnType("date");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Employees", t =>
                        {
                            t.HasCheckConstraint("CK_CommissionEmployee_Rate", "Rate >= 0 AND Rate <= 1");

                            t.HasCheckConstraint("CK_CommissionEmployee_Target", "Target >= 0");

                            t.HasCheckConstraint("CK_Employee_Email", "Email LIKE '%@%_%.__%' AND Email NOT LIKE '%@%@%'");

                            t.HasCheckConstraint("CK_Employee_HireDate", "DateOfHire >= DATEADD(YEAR,18,DateOfBirth)");

                            t.HasCheckConstraint("CK_Employee_PhoneNumber", "PhoneNumber LIKE '+[0-9]%'");

                            t.HasCheckConstraint("CK_HourlyEmployee_HourlyRate", "HourlyRate >= 0");

                            t.HasCheckConstraint("CK_HourlyEmployee_HoursWorked", "HoursWorked >= 0");

                            t.HasCheckConstraint("CK_ManagerEmployee_Bonus", "Bonus >= 0");

                            t.HasCheckConstraint("CK_ManagerEmployee_MonthlySalary", "MonthlySalary >= 0");

                            t.HasCheckConstraint("CK_SalariedEmployee_MonthlySalary", "MonthlySalary >= 0");
                        });

                    b.HasDiscriminator().HasValue("Employee");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HRManagementSystem.Domains.Entities.EmployeeBenefit", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("BenefitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("EmployeeId", "BenefitId");

                    b.HasIndex("BenefitId");

                    b.HasIndex("EmployeeId", "IsActive");

                    b.ToTable("EmployeeBenefits", t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeBenefit_EnrollmentDate", "EnrollmentDate <= GETDATE()");
                        });
                });

            modelBuilder.Entity("HRManagementSystem.Domains.Entities.DentalBenefit", b =>
                {
                    b.HasBaseType("HRManagementSystem.Domains.Entities.Benefit");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Benefit_Amount", "Amount >= 0");
                        });

                    b.HasDiscriminator().HasValue("Dental");
                });

            modelBuilder.Entity("HRManagementSystem.Domains.Entities.HealthBenefit", b =>
                {
                    b.HasBaseType("HRManagementSystem.Domains.Entities.Benefit");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Benefit_Amount", "Amount >= 0");
                        });

                    b.HasDiscriminator().HasValue("Health");
                });

            modelBuilder.Entity("HRManagementSystem.Domains.Entities.VisionBenefit", b =>
                {
                    b.HasBaseType("HRManagementSystem.Domains.Entities.Benefit");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Benefit_Amount", "Amount >= 0");
                        });

                    b.HasDiscriminator().HasValue("Vision");
                });

            modelBuilder.Entity("HRManagementSystem.Domains.Entities.CommissionEmployee", b =>
                {
                    b.HasBaseType("HRManagementSystem.Domains.Entities.Employee");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Target")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_CommissionEmployee_Rate", "Rate >= 0 AND Rate <= 1");

                            t.HasCheckConstraint("CK_CommissionEmployee_Target", "Target >= 0");

                            t.HasCheckConstraint("CK_Employee_Email", "Email LIKE '%@%_%.__%' AND Email NOT LIKE '%@%@%'");

                            t.HasCheckConstraint("CK_Employee_HireDate", "DateOfHire >= DATEADD(YEAR,18,DateOfBirth)");

                            t.HasCheckConstraint("CK_Employee_PhoneNumber", "PhoneNumber LIKE '+[0-9]%'");

                            t.HasCheckConstraint("CK_HourlyEmployee_HourlyRate", "HourlyRate >= 0");

                            t.HasCheckConstraint("CK_HourlyEmployee_HoursWorked", "HoursWorked >= 0");

                            t.HasCheckConstraint("CK_ManagerEmployee_Bonus", "Bonus >= 0");

                            t.HasCheckConstraint("CK_ManagerEmployee_MonthlySalary", "MonthlySalary >= 0");

                            t.HasCheckConstraint("CK_SalariedEmployee_MonthlySalary", "MonthlySalary >= 0");
                        });

                    b.HasDiscriminator().HasValue("Commission");
                });

            modelBuilder.Entity("HRManagementSystem.Domains.Entities.HourlyEmployee", b =>
                {
                    b.HasBaseType("HRManagementSystem.Domains.Entities.Employee");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HoursWorked")
                        .HasColumnType("int");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_CommissionEmployee_Rate", "Rate >= 0 AND Rate <= 1");

                            t.HasCheckConstraint("CK_CommissionEmployee_Target", "Target >= 0");

                            t.HasCheckConstraint("CK_Employee_Email", "Email LIKE '%@%_%.__%' AND Email NOT LIKE '%@%@%'");

                            t.HasCheckConstraint("CK_Employee_HireDate", "DateOfHire >= DATEADD(YEAR,18,DateOfBirth)");

                            t.HasCheckConstraint("CK_Employee_PhoneNumber", "PhoneNumber LIKE '+[0-9]%'");

                            t.HasCheckConstraint("CK_HourlyEmployee_HourlyRate", "HourlyRate >= 0");

                            t.HasCheckConstraint("CK_HourlyEmployee_HoursWorked", "HoursWorked >= 0");

                            t.HasCheckConstraint("CK_ManagerEmployee_Bonus", "Bonus >= 0");

                            t.HasCheckConstraint("CK_ManagerEmployee_MonthlySalary", "MonthlySalary >= 0");

                            t.HasCheckConstraint("CK_SalariedEmployee_MonthlySalary", "MonthlySalary >= 0");
                        });

                    b.HasDiscriminator().HasValue("Hourly");
                });

            modelBuilder.Entity("HRManagementSystem.Domains.Entities.ManagerEmployee", b =>
                {
                    b.HasBaseType("HRManagementSystem.Domains.Entities.Employee");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlySalary")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_CommissionEmployee_Rate", "Rate >= 0 AND Rate <= 1");

                            t.HasCheckConstraint("CK_CommissionEmployee_Target", "Target >= 0");

                            t.HasCheckConstraint("CK_Employee_Email", "Email LIKE '%@%_%.__%' AND Email NOT LIKE '%@%@%'");

                            t.HasCheckConstraint("CK_Employee_HireDate", "DateOfHire >= DATEADD(YEAR,18,DateOfBirth)");

                            t.HasCheckConstraint("CK_Employee_PhoneNumber", "PhoneNumber LIKE '+[0-9]%'");

                            t.HasCheckConstraint("CK_HourlyEmployee_HourlyRate", "HourlyRate >= 0");

                            t.HasCheckConstraint("CK_HourlyEmployee_HoursWorked", "HoursWorked >= 0");

                            t.HasCheckConstraint("CK_ManagerEmployee_Bonus", "Bonus >= 0");

                            t.HasCheckConstraint("CK_ManagerEmployee_MonthlySalary", "MonthlySalary >= 0");

                            t.HasCheckConstraint("CK_SalariedEmployee_MonthlySalary", "MonthlySalary >= 0");
                        });

                    b.HasDiscriminator().HasValue("Manager");
                });

            modelBuilder.Entity("HRManagementSystem.Domains.Entities.SalariedEmployee", b =>
                {
                    b.HasBaseType("HRManagementSystem.Domains.Entities.Employee");

                    b.Property<decimal>("MonthlySalary")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("Employees", t =>
                        {
                            t.HasCheckConstraint("CK_CommissionEmployee_Rate", "Rate >= 0 AND Rate <= 1");

                            t.HasCheckConstraint("CK_CommissionEmployee_Target", "Target >= 0");

                            t.HasCheckConstraint("CK_Employee_Email", "Email LIKE '%@%_%.__%' AND Email NOT LIKE '%@%@%'");

                            t.HasCheckConstraint("CK_Employee_HireDate", "DateOfHire >= DATEADD(YEAR,18,DateOfBirth)");

                            t.HasCheckConstraint("CK_Employee_PhoneNumber", "PhoneNumber LIKE '+[0-9]%'");

                            t.HasCheckConstraint("CK_HourlyEmployee_HourlyRate", "HourlyRate >= 0");

                            t.HasCheckConstraint("CK_HourlyEmployee_HoursWorked", "HoursWorked >= 0");

                            t.HasCheckConstraint("CK_ManagerEmployee_Bonus", "Bonus >= 0");

                            t.HasCheckConstraint("CK_ManagerEmployee_MonthlySalary", "MonthlySalary >= 0");

                            t.HasCheckConstraint("CK_SalariedEmployee_MonthlySalary", "MonthlySalary >= 0");

                            t.Property("MonthlySalary")
                                .HasColumnName("SalariedEmployee_MonthlySalary");
                        });

                    b.HasDiscriminator().HasValue("Salaried");
                });

            modelBuilder.Entity("HRManagementSystem.Domains.Entities.Department", b =>
                {
                    b.HasOne("HRManagementSystem.Domains.Entities.ManagerEmployee", "Manager")
                        .WithOne()
                        .HasForeignKey("HRManagementSystem.Domains.Entities.Department", "ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("HRManagementSystem.Domains.Entities.Employee", b =>
                {
                    b.HasOne("HRManagementSystem.Domains.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HRManagementSystem.Domains.Entities.ManagerEmployee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("HRManagementSystem.Domains.Entities.EmployeeBenefit", b =>
                {
                    b.HasOne("HRManagementSystem.Domains.Entities.Benefit", "Benefit")
                        .WithMany("EmployeeBenefits")
                        .HasForeignKey("BenefitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Domains.Entities.Employee", "Employee")
                        .WithMany("EmployeeBenefits")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benefit");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRManagementSystem.Domains.Entities.Benefit", b =>
                {
                    b.Navigation("EmployeeBenefits");
                });

            modelBuilder.Entity("HRManagementSystem.Domains.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HRManagementSystem.Domains.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeBenefits");
                });

            modelBuilder.Entity("HRManagementSystem.Domains.Entities.ManagerEmployee", b =>
                {
                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
